# Generated by Django 5.1.5 on 2025-01-20 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Milestone',
        ),
        migrations.AddField(
            model_name='guestmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
