# Generated by Django 5.1.5 on 2025-01-22 08:58

import pyuploadcare.dj.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_delete_milestone_guestmessage_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery/'),
        ),
    ]
